export OMP_NUM_THREADS=1
make clean; make -j ENABLE_BETTER_OPT=1 ENABLE_STACK=1 ENABLE_COMMON=1 ENABLE_REMOVE_INSERTION_SORT=1 ENABLE_OMP=1
bash run.sh
export OMP_NUM_THREADS=2
make clean; make -j ENABLE_BETTER_OPT=1 ENABLE_STACK=1 ENABLE_COMMON=1 ENABLE_REMOVE_INSERTION_SORT=1 ENABLE_OMP=1
bash run.sh
export OMP_NUM_THREADS=3
make clean; make -j ENABLE_BETTER_OPT=1 ENABLE_STACK=1 ENABLE_COMMON=1 ENABLE_REMOVE_INSERTION_SORT=1 ENABLE_OMP=1
bash run.sh
export OMP_NUM_THREADS=4
make clean; make -j ENABLE_BETTER_OPT=1 ENABLE_STACK=1 ENABLE_COMMON=1 ENABLE_REMOVE_INSERTION_SORT=1 ENABLE_OMP=1
bash run.sh